name: Test mtime

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version (i.e. v0.22.3-pre.2)"
        required: true  

jobs:
  test-mtime:
    name: Test mtime
    runs-on: [ self-hosted, linux, x64, ubuntu-mtime ]
    timeout-minutes: 120
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Build Docker image
        uses: ./.github/actions/docker
        with:
          image: dashpay/mtime-test
          push: false
          image_tag: ${{ github.event.inputs.tag }}
          platforms: amd64
          cache_mounts: |
            cargo_registry_index
            cargo_registry_cache
            cargo_git
            target_amd64

      - name: Run generated artifact
        run: |
          docker run dashpay/mtime-test:0
